### PR TITLE
Reorder conversion methods in ParamConverter and binary check for logging

### LINKED ISSUE #57: \Ray\MediaQuery\MediaQueryLogger causing problems with Uuids
I've juststarted playing with BEAR.Sunday, so please excude my lack of knowledge & possibly understanding.

### Bug Report

I am using (binary) Uuids for Ids in my new app, and whilst I have this working OK for saving the values to the d/b, an error is being throw because the `MediaQueryLogger` cannot json_encode the binary string.

I thought I could use AOP to intercept the Uuid values being passed to logger, however there are 2 problems with this…

1. The values being passed are the converted ones, not the original ones, so they'll need 'unconverting' (which I'm doing in a decorator of the `MediaQueryLogger`);
2. The `MediaQueryLogger` class is final, so it's not possible to intercept the `log()` method call.

### How to reproduce

1. Create the following files & classes…

    ```sql
    # asset_create.sql
    INSERT INTO assets (id, name, createdAt, updatedAt)
    VALUES (:id, :name, :createdAt, :updatedAt);
    ```
    
    ```php
    <?php
    // src/Resource/App/Assets.php
    
    declare(strict_types=1);
    
    namespace TobyGriffiths\NetWorth\Resource\App;
    
    use BEAR\Package\Annotation\ReturnCreatedResource;
    use BEAR\Resource\ResourceObject;
    use DateTimeInterface;
    use Koriym\HttpConstants\ResponseHeader;
    use Koriym\HttpConstants\StatusCode;
    use TobyGriffiths\NetWorth\Query\AssetCommandInterface;
    use TobyGriffiths\NetWorth\Uuid\UuidFactory;
    
    use function uri_template;
    
    class Assets extends ResourceObject
    {
        public function __construct(
            private UuidFactory $uuidFactory,
            private readonly AssetCommandInterface $command,
            private readonly DateTimeInterface $now,
        ) {
        }
    
        public function onPost(string $name): static
        {
            $id = $this->uuidFactory->uuid7($this->now);
            $this->command->create($id, $name);
    
            $this->code = StatusCode::CREATED;
            $this->headers[ResponseHeader::LOCATION] = uri_template('/assets{?id}', ['id' => $id->toString()]);
    
            return $this;
        }
    }
    ```
    
    ```php
    <?php
    // src/Uuid/UuidFactory.php
    
    declare(strict_types=1);
    
    namespace TobyGriffiths\NetWorth\Uuid;
    
    use DateTimeImmutable;
    use Ramsey\Uuid\UuidFactory as RamseyUuidFactory;
    
    final readonly class UuidFactory implements UuidFactoryInterface
    {
        public function __construct(
            private RamseyUuidFactory $innerFactory,
        ) {
        }
    
        public function uuid7(DateTimeImmutable|null $dateTime = null): Uuid
        {
            return new Uuid($this->innerFactory->uuid7($dateTime));
        }
    }
    ```
    
    ```php
    // src/Uuid/Uuid.php
    <?php
    
    declare(strict_types=1);
    
    namespace TobyGriffiths\NetWorth\Uuid;
    
    use Ramsey\Uuid\UuidInterface as RamseyUuidInterface;
    
    final readonly class Uuid
    {
        public function __construct(
            private RamseyUuidInterface $innerUuid,
        ) {
        }
    
        public function toString(): string
        {
            return $this->innerUuid->toString();
        }
    
        public function toScalar(): string
        {
            return $this->innerUuid->getBytes();
        }
    }
    ```

2. Bind the necessary services…

    ```php
    <?php
    
    declare(strict_types=1);
    
    namespace TobyGriffiths\NetWorth\Module;
    
    use BEAR\Dotenv\Dotenv;
    use BEAR\Package\AbstractAppModule;
    use BEAR\Package\PackageModule;
    use BEAR\Resource\Module\JsonSchemaModule;
    use Ramsey\Uuid\UuidFactory as RamseyUuidFactory;
    use Ramsey\Uuid\UuidFactoryInterface as RamseyUuidFactoryInterface;
    use Ray\AuraSqlModule\AuraSqlModule;
    use Ray\Di\ProviderInterface;
    use Ray\Di\Scope;
    use Ray\IdentityValueModule\IdentityValueModule;
    use Ray\MediaQuery\DbQueryConfig;
    use Ray\MediaQuery\MediaQueryLogger;
    use Ray\MediaQuery\MediaQueryLoggerInterface;
    use Ray\MediaQuery\MediaQueryModule;
    use Ray\MediaQuery\Queries;
    use TobyGriffiths\NetWorth\MediaQuery\BinaryDataMediaQueryLoggerDecorator;
    use TobyGriffiths\NetWorth\Uuid\UuidFactory;
    use TobyGriffiths\NetWorth\Uuid\UuidFactoryInterface;
    
    use function dirname;
    use function getenv;
    
    class AppModule extends AbstractAppModule
    {
        protected function configure(): void
        {
            (new Dotenv())->load(dirname(__DIR__, 2));
    
            $this->overrideMediaQueryLogger();
    
            $this->installDbModules();
    
            $this->bind(UuidFactoryInterface::class)->to(UuidFactory::class)->in(Scope::SINGLETON);
            $this->bind(RamseyUuidFactoryInterface::class)->to(RamseyUuidFactory::class)->in(Scope::SINGLETON);
    
            $this->install(new PackageModule());
        }
    
        private function installDbModules(): void
        {
            $this->install(
                new AuraSqlModule(
                    (string) getenv('DB_DSN'),
                    (string) getenv('DB_USER'),
                    (string) getenv('DB_PW'),
                    (string) getenv('DB_SLAVE'),
                ),
            );
    
            $this->install(
                new MediaQueryModule(
                    Queries::fromDir($this->appMeta->appDir . '/src/Query'),
                    [
                        new DbQueryConfig($this->appMeta->appDir . '/var/sql'),
                    ],
                ),
            );
    
            $this->install(new IdentityValueModule());
    
            $this->install(
                new JsonSchemaModule(
                    $this->appMeta->appDir . '/var/schema/response',
                    $this->appMeta->appDir . '/var/schema/request',
                ),
            );
        }
    
        private function overrideMediaQueryLogger(): void
        {
        // Commenting this fix out to demo the problem
        //
        //    $this
        //        ->bind(MediaQueryLoggerInterface::class)
        //        ->to(BinaryDataMediaQueryLoggerDecorator::class)
        //        ->in(Scope::SINGLETON);
        //    $this->bind(MediaQueryLogger::class);
        }
    }
    ```

3. Call the endpoint…

```shell
$ php ./bin/app/php post '/assets?name=wibble'
```

You can see I've commented out a call to `overrideMediaQueryLogger()`, which binds the following class to fix the issue, for now…

```php
<?php

declare(strict_types=1);

namespace TobyGriffiths\NetWorth\MediaQuery;

use InvalidArgumentException;
use Ramsey\Uuid\UuidFactory;
use Ray\MediaQuery\MediaQueryLogger as RayMediaQueryLogger;
use Ray\MediaQuery\MediaQueryLoggerInterface;

use function mb_check_encoding;

/**
 * Drop in replacement of Ray\MediaQuery\MediaQueryLogger that can handle binary Uuid values.
 */
final class BinaryDataMediaQueryLoggerDecorator implements MediaQueryLoggerInterface
{
    public function __construct(
        private readonly RayMediaQueryLogger $decorated,
        // We use the concrete class here because that has needed to be bound
        private readonly UuidFactory $uuidFactory,
    ) {
    }

    public function start(): void
    {
        $this->decorated->start();
    }

    /**
     * {@inheritDoc}
     */
    public function log(string $queryId, array $values): void
    {
        foreach ($values as &$value) {
            if (mb_check_encoding($value, 'UTF-8')) {
                continue;
            }

            // Replace this with injected handlers for different types of binary data?
            try {
                $value = $this->uuidFactory
                    ->fromBytes($value)
                    ->toString();
            } catch (InvalidArgumentException) {
                // Don't convert the value, we'll just fail for now.
            }
        }
    }

    public function __toString(): string
    {
        return $this->decorated->__toString();
    }
}
```

So I have a proposed solution, which I'm happy to PR…

1. Remove the `final` from `MediaQueryLogger`;
2. Include the original values in the call to `MediaQueryLoggerInterface::log()`, optional, so as not to break anyone's
   overrides…

    ```php
    public function log(string $queryId, array $values, array $originalValues = []): void;
    ```

I also found it difficult to work out how to decorate the original `MediaQueryLogger` instance, which is straight pretty
forward in Symfony, so if anyone can enlighten me on that, I can improve my workaround until this has a better fix?

If I can provide any more context info, or test some things, please let me know.

### PR DESCRIPTION
**Pull request by koriym**
Close #57 

## BC Berak

This PR breaks backwards compatibility ( even though it is minor) as it changes the order of processing in ParamConverter. The release is incremented by the minor version.

## Summary by CodeRabbit

- **New Features**
	- Enhanced the logging mechanism to include encoding of values for better data integrity and security.
- **Bug Fixes**
	- Improved parameter conversion logic by optimizing the order of checks, enhancing the handling and conversion of data types.
- **Chores**
	- Updated system requirements to include the `ext-mbstring` PHP extension for better multilingual support.

### CODE REVIEW

**Comment by koriym** [comment]
@coderabbitai review

**Comment by koriym** [comment]
@toby-griffiths What do you think?

**Comment by toby-griffiths** [comment]
@koriym Looks good to me.  I think the AI bot has a point about the readabilty of the comment.  It's suggested reads better to me than the original.

**Comment by koriym** [comment]
@NaokiTsuchiya merged!

**Comment by koriym** [comment]
@toby-griffiths Do you think this interface change is still necessary?

```php
public function log(string $queryId, array $values, array $originalValues = []): void;
```

**Pull request merged**
